export const playerData = [
    {
        playerName: "Rakan",
        playerRankings: [
            "Lexi Love",
            "Lana Ja'Rae",
            "Jewels Sparkles",
            "Lucky Starzzz",
            "Suzie Toot",
            "Kori King",
            "Arrietty",
            "Lydia B Kollins",
            "Sam Star",
            "Joella",
            "Crystal Envy",
            "Acacia Forgot",
            "Hormona Lisa",
            "Onya Nurve",
        ],
        playerWinners: [
            "Arrietty",
            "Suzie Toot",
            "Jewels Sparkles",
            "Arrietty"
        ],
        MissC: 'Suzie Toot',
        GoldenBoot: 'Onya Nurve',
        leverQueen: 'Arrietty',
        leverNum: 3,
        lipSyncAssasin: 'Jewels Sparkles',
        bonusPoints: 5
    },
    {
        playerName: "Chace",
        playerRankings: [
            "Lexi Love",
            "Jewels Sparkles",
            "Lana Ja'Rae",
            "Sam Star",
            "Suzie Toot",
            "Arrietty",
            "Onya Nurve",
            "Lydia B Kollins",
            "Kori King",
            "Crystal Envy",
            "Lucky Starzzz",
            "Acacia Forgot",
            "Hormona Lisa",
            "Joella",
        ],
        playerWinners: [
            "Arrietty",
            "Suzie Toot",
            "Onya Nurve",
            "Arrietty"
        ],
        MissC: 'Suzie Toot',
        GoldenBoot: 'Kori King',
        leverQueen: 'Arrietty',
        leverNum: 1,
        lipSyncAssasin: 'Onya Nurve',
        bonusPoints: 10
    },
    {
        playerName: "Justin",
        playerRankings: [
            "Lexi Love",
            "Jewels Sparkles",
            "Sam Star",
            "Kori King",
            "Lana Ja'Rae",
            "Onya Nurve",
            "Arrietty",
            "Lucky Starzzz",
            "Lydia B Kollins",
            "Crystal Envy",
            "Suzie Toot",
            "Acacia Forgot",
            "Joella",
            "Hormona Lisa",
        ],
        playerWinners: [
            "Arrietty",
            "Lexi Love",
            "Onya Nurve",
            "Lydia B Kollins"
        ],
        MissC: 'Jewels Sparkles',
        GoldenBoot: 'Suzie Toot',
        leverQueen: 'Lana Ja\'Rae',
        leverNum: 3,
        lipSyncAssasin: 'Kori King',
        bonusPoints: 0
    },
    {
        playerName: "Minh",
        playerRankings: [
            "Lexi Love",
            "Jewels Sparkles",
            "Onya Nurve",
            "Suzie Toot",
            "Lana Ja'Rae",
            "Lydia B Kollins",
            "Arrietty",
            "Crystal Envy",
            "Kori Kong",
            "Lucky Starzzz",
            "Hormona Lisa",
            "Sam Star",
            "Acacia Forgot",
            "Joella",
        ],
        playerWinners: [
            "Arrietty",
            "Lexi Love",
            "Onya Nurve",
            "Arrietty"
        ],
        MissC: 'Lucky Starzzz',
        GoldenBoot: 'Joella',
        leverQueen: 'Lydia B Kollins',
        leverNum: 3,
        lipSyncAssasin: 'Lana Ja\'Rae',
        bonusPoints: 0
    },
    {
        playerName: "Hannah Homie G",
        playerRankings: [
            "Lexi Love",
            "Jewels Sparkles",
            "Suzie Toot",
            "Sam Star",
            "Crystal Envy",
            "Lydia B Kollins",
            "Lucky Starzzz",
            "Onya Nurve",
            "Arrietty",
            "Kori King",
            "Joella",
            "Hormona Lisa",
            "Lana Ja'Rae",
            "Acacia Forgot",
        ],
        playerWinners: [
            "Arrietty",
            "Sam Star",
            "Suzie Toot",
            "Arrietty"
        ],
        MissC: 'Onya Nurve',
        GoldenBoot: 'Acacia Forgot',
        leverQueen: 'Jewels Sparkles',
        leverNum: 1,
        lipSyncAssasin: 'Crystal Envy',
        bonusPoints: 5
    },
    {
        playerName: "JV",
        playerRankings: [
            "Lexi Love",
            "Arrietty",
            "Jewels Sparkles",
            "Sam Star",
            "Crystal Envy",
            "Lana Ja'Rae",
            "Kori King",
            "Suzie Toot",
            "Lydia B Kollins",
            "Lucky Starzzz",
            "Onya Nurve",
            "Joella",
            "Hormona Lisa",
            "Acacia Forgot",
        ],
        playerWinners: [
            "Arrietty",
            "Lexi Love",
            "Jewels Sparkles",
            "Lexi Love"
        ],
        MissC: 'Lexi Love',
        GoldenBoot: 'Acacia Forgot',
        leverQueen: 'Arrietty',
        leverNum: 1,
        lipSyncAssasin: 'Jewels Sparkles',
        bonusPoints: 10
    },
    {
        playerName: "Ben",
        playerRankings: [
            "Lexi Love",
            "Kori King",
            "Lucky Starzzz",
            "Suzie Toot",
            "Sam Star",
            "Jewels Sparkles",
            "Lana Ja'Rae",
            "Lydia B Kollins",
            "Arrietty",
            "Crystal Envy",
            "Joella",
            "Acacia Forgot",
            "Hormona Lisa",
            "Onya Nurve",
        ],
        playerWinners: [
            "Arrietty",
            "Kori King",
            "Jewels Sparkles",
            "Lucky Starzzz"
        ],
        MissC: 'Suzie Toot',
        GoldenBoot: 'Acacia Forgot',
        leverQueen: 'Jewels Sparkles',
        leverNum: 3,
        lipSyncAssasin: 'Jewels Sparkles',
        bonusPoints: 0
    },
    {
        playerName: "Sam",
        playerRankings: [
            "Lexi Love",
            "Jewels Sparkles",
            "Sam Star",
            "Kori King",
            "Lana Ja'Rae",
            "Suzie Toot",
            "Lucky Starzzz",
            "Crystal Envy",
            "Arrietty",
            "Lydia B Kollins",
            "Onya Nurve",
            "Acacia Forgot",
            "Hormona Lisa",
            "Joella",
        ],
        playerWinners: [
            "Arrietty",
            "Suzie Toot",
            "Lexi Love",
            "Sam Star"
        ],
        MissC: 'Lexi Love',
        GoldenBoot: 'Hormona Lisa',
        leverQueen: 'Lana Ja\'Rae',
        leverNum: 4,
        lipSyncAssasin: 'Arrietty',
        bonusPoints: 0
    },
    {
        playerName: "Kdawg",
        playerRankings: [
            "Lexi Love",
            "Suzie Toot",
            "Crystal Envy",
            "Jewels Sparkles",
            "Sam Star",
            "Lucky Starzzz",
            "Lydia B Kollins",
            "Kori King",
            "Arrietty",
            "Lana Ja'Rae",
            "Onya Nurve",
            "Joella",
            "Hormona Lisa",
            "Acacia Forgot",
        ],
        playerWinners: [
            "Sam Star",
            "Suzie Toot",
            "Suzie Toot",
            "Lucky Starzzz"
        ],
        MissC: 'Lexi Love',
        GoldenBoot: 'Lana Ja\'Rae',
        leverQueen: 'Joella',
        leverNum: 4,
        lipSyncAssasin: 'Crystal Envy',
        bonusPoints: 0
    },
    {
        playerName: "Imma",
        playerRankings: [
            "Suzie Toot",
            "Lexi Love",
            "Kori King",
            "Jewels Sparkles",
            "Crystal Envy",
            "Arrietty",
            "Lydia B Kollins",
            "Lana Ja'Rae",
            "Lucky Starzzz",
            "Sam Star",
            "Joella",
            "Hormona Lisa",
            "Acacia Forgot",
            "Onya Nurve",
        ],
        playerWinners: [
            "Arrietty",
            "Suzie Toot",
            "Kori King",
            "Arrietty"
        ],
        MissC: 'Lexi Love',
        GoldenBoot: 'Joella',
        leverQueen: 'Crystal Envy',
        leverNum: 2,
        lipSyncAssasin: 'Arrietty',
        bonusPoints: 0
    },
    {
        playerName: "Nathan",
        playerRankings: [
            "Lexi Love",
            "Kori King",
            "Jewels Sparkles",
            "Crystal Envy",
            "Suzie Toot",
            "Sam Star",
            "Lana Ja'Rae",
            "Arrietty",
            "Lucky Starzzz",
            "Lydia B Kollins",
            "Joella",
            "Acacia Forgot",
            "Onya Nurve",
            "Hormona Lisa",
        ],
        playerWinners: [
            "Jewels Sparkles",
            "Sam Star",
            "Arrietty",
            "Lana Ja'Rae"
        ],
        MissC: 'Lucky Starzzz',
        GoldenBoot: 'Joella',
        leverQueen: 'Arrietty',
        leverNum: 2,
        lipSyncAssasin: 'Lucky Starzzz',
        bonusPoints: 5
    },
    {
        playerName: "Roudell",
        playerRankings: [
            "Lexi Love",
            "Jewels Sparkles",
            "Suzie Toot",
            "Lucky Starzzz",
            "Arrietty",
            "Kori King",
            "Lana Ja'Rae",
            "Crystal Envy",
            "Onya Nurve",
            "Sam Star",
            "Lydia B Kollins",
            "Hormona Lisa",
            "Acacia Forgot",
            "Joella",
        ],
        playerWinners: [
            "Arrietty",
            "Suzie Toot",
            "Kori King",
            "Lucky Starzzz"
        ],
        MissC: 'Arrietty',
        GoldenBoot: 'Joella',
        leverQueen: 'Arrietty',
        leverNum: 6,
        lipSyncAssasin: 'Acacia Forgot',
        bonusPoints: 5
    },
    {
        playerName: "Alessandra",
        playerRankings: [
            "Lexi Love",
            "Kori King",
            "Jewels Sparkles",
            "Sam Star",
            "Lucky Starzzz",
            "Suzie Toot",
            "Lana Ja'Rae",
            "Arrietty",
            "Onya Nurve",
            "Crystal Envy",
            "Lydia B Kollins",
            "Joella",
            "Acacia Forgot",
            "Hormona Lisa",
        ],
        playerWinners: [
            "Arrietty",
            "Kori King",
            "Jewels Sparkles",
            "Lucky Starzzz"
        ],
        MissC: 'Lexi Love',
        GoldenBoot: 'Onya Nurve',
        leverQueen: 'Lana Ja\'Rae',
        leverNum: 4,
        lipSyncAssasin: 'Jewels Sparkles',
        bonusPoints: 0
    },
    {
        playerName: "Hannah Kelly",
        playerRankings: [
            "Lexi Love",
            "Jewels Sparkles",
            "Sam Star",
            "Onya Nurve",
            "Suzie Toot",
            "Lana Ja'Rae",
            "Arrietty",
            "Lydia B Kollins",
            "Kori King",
            "Crystal Envy",
            "Acacia Forgot",
            "Lucky Starzzz",
            "Hormona Lisa",
            "Joella",
        ],
        playerWinners: [
            "Arrietty",
            "Jewels Sparkles",
            "Hormona Lisa",
            "Lydia B Kollins"
        ],
        MissC: 'Lydia B Kollins',
        GoldenBoot: 'Lucky Starzzz',
        leverQueen: 'Lana Ja\'Rae',
        leverNum: 4,
        lipSyncAssasin: 'Onya Nurve',
        bonusPoints: 0
    },
    {
        playerName: "Tariq",
        playerRankings: [
            "Lexi Love",
            "Kori King",
            "Jewels Sparkles",
            "Arrietty",
            "Onya Nurve",
            "Sam Star",
            "Lydia B Kollins",
            "Suzie Toot",
            "Crystal Envy",
            "Joella",
            "Lana Ja'Rae",
            "Hormona Lisa",
            "Acacia Forgot",
            "",
        ],
        playerWinners: [
            "Arrietty",
            "Suzie Toot",
            "Lexi Love",
            ""
        ],
        MissC: 'Kori King', 
        GoldenBoot: 'Joella',
        leverQueen: 'Onya Nurve',
        leverNum: 1,
        lipSyncAssasin: 'Jewels Sparkles',
        bonusPoints: 5
    },
] 