export const playerData = [
    {
        playerName: "Rakan",
        playerRankings: [
            "Lexi Love",
            "Lana Ja'Rae",
            "Jewels Sparkles",
            "Onya Nurve",
            "Suzie Toot",
            "Kori King",
            "Arrietty",
            "Lydia B Kollins",
            "Sam Star",
            "Joella",
            "Crystal Envy",
            "Acacia Forgot",
            "Hormona Lisa",
            "Lucky Starzzz",
        ],
        playerWinners: [
            "Jewels Sparkles",
            "Onya Nurve",
            "Arrietty",
            "Suzie Toot",
            "Jewels Sparkles",
            "Arrietty"
        ],
        MissC: "Suzie Toot",
        GoldenBoot: "Onya Nurve",
        leverQueen: "Arrietty",
        leverNum: 3,
        lipSyncAssasin: "Jewels Sparkles",
        firstQueensSwaped: "Lucky Starzzz",
        secondQueensSwaped: "Onya Nurve"
    },
    {
        playerName: "Chace",
        playerRankings: [
            "Lexi Love",
            "Jewels Sparkles",
            "Onya Nurve",
            "Sam Star",
            "Suzie Toot",
            "Arrietty",
            "Lana Ja'Rae",
            "Lydia B Kollins",
            "Kori King",
            "Crystal Envy",
            "Lucky Starzzz",
            "Acacia Forgot",
            "Hormona Lisa",
            "Joella",
        ],
        playerWinners: [
            "Jewels Sparkles",
            "Suzie Toot",
            "Arrietty",
            "Suzie Toot",
            "Onya Nurve",
            "Arrietty"
        ],
        MissC: "Suzie Toot",
        GoldenBoot: "Kori King",
        leverQueen: "Arrietty",
        leverNum: 1,
        lipSyncAssasin: "Onya Nurve",
        firstQueensSwaped: "Lana Ja'Rae",
        secondQueensSwaped: "Onya Nurve"
    },
    {
        playerName: "Justin",
        playerRankings: [
            "Lexi Love",
            "Jewels Sparkles",
            "Sam Star",
            "Kori King",
            "Lana Ja'Rae",
            "Onya Nurve",
            "Arrietty",
            "Suzie Toot",
            "Lydia B Kollins",
            "Crystal Envy",
            "Lucky Starzzz",
            "Acacia Forgot",
            "Joella",
            "Hormona Lisa",
        ],
        playerWinners: [
            "Suzie Toot",
            "Onya Nurve",
            "Arrietty",
            "Lexi Love",
            "Onya Nurve",
            "Lydia B Kollins"
        ],
        MissC: "Jewels Sparkles",
        GoldenBoot: "Suzie Toot",
        leverQueen: "Lana Ja'Rae",
        leverNum: 3,
        lipSyncAssasin: "Kori King",
        firstQueensSwaped: "Suzie Toot",
        secondQueensSwaped: "Lucky Starzzz"
    },
    {
        playerName: "Minh",
        playerRankings: [
            "Lexi Love",
            "Jewels Sparkles",
            "Onya Nurve",
            "Suzie Toot",
            "Lana Ja'Rae",
            "Lydia B Kollins",
            "Arrietty",
            "Sam Star",
            "Kori Kong",
            "Lucky Starzzz",
            "Hormona Lisa",
            "Crystal Envy",
            "Acacia Forgot",
            "Joella",
        ],
        playerWinners: [
            "Sam Star",
            "Onya Nurve",
            "Arrietty",
            "Lexi Love",
            "Onya Nurve",
            "Arrietty"
        ],
        MissC: "Lucky Starzzz",
        GoldenBoot: "Joella",
        leverQueen: "Lydia B Kollins",
        leverNum: 3,
        lipSyncAssasin: "Lana Ja'Rae",
        firstQueensSwaped: "Sam Star",
        secondQueensSwaped: "Crystal Envy"
    },
    {
        playerName: "Hannah Homie G",
        playerRankings: [
            "Onya Nurve",
            "Jewels Sparkles",
            "Suzie Toot",
            "Sam Star",
            "Crystal Envy",
            "Lydia B Kollins",
            "Lucky Starzzz",
            "Lexi Love",
            "Arrietty",
            "Kori King",
            "Joella",
            "Hormona Lisa",
            "Lana Ja'Rae",
            "Acacia Forgot",
        ],
        playerWinners: [
            "Jewels Sparkles",
            "Suzie Toot",
            "Arrietty",
            "Sam Star",
            "Suzie Toot",
            "Arrietty"
        ],
        MissC: "Onya Nurve",
        GoldenBoot: "Acacia Forgot",
        leverQueen: "Jewels Sparkles",
        leverNum: 1,
        lipSyncAssasin: "Crystal Envy",
        firstQueensSwaped: "Onya Nurve",
        secondQueensSwaped: "Lexi Love"
    },
    {
        playerName: "JV",
        playerRankings: [
            "Lexi Love",
            "Arrietty",
            "Jewels Sparkles",
            "Sam Star",
            "Acacia Forgot",
            "Lana Ja'Rae",
            "Kori King",
            "Suzie Toot",
            "Lydia B Kollins",
            "Lucky Starzzz",
            "Onya Nurve",
            "Joella",
            "Hormona Lisa",
            "Crystal Envy",
        ],
        playerWinners: [
            "Sam Star",
            "Suzie Toot",
            "Arrietty",
            "Lexi Love",
            "Jewels Sparkles",
            "Lexi Love"
        ],
        MissC: "Lexi Love",
        GoldenBoot: "Acacia Forgot",
        leverQueen: "Arrietty",
        leverNum: 1,
        lipSyncAssasin: "Jewels Sparkles",
        firstQueensSwaped: "Crystal Envy",
        secondQueensSwaped: "Acacia Forgot"
    },
    {
        playerName: "Ben",
        playerRankings: [
            "Lexi Love",
            "Kori King",
            "Onya Nurve",
            "Suzie Toot",
            "Sam Star",
            "Jewels Sparkles",
            "Lana Ja'Rae",
            "Lydia B Kollins",
            "Arrietty",
            "Crystal Envy",
            "Joella",
            "Acacia Forgot",
            "Hormona Lisa",
            "Lucky Starzzz",
        ],
        playerWinners: [
            "Sam Star",
            "Onya Nurve",
            "Arrietty",
            "Kori King",
            "Jewels Sparkles",
            "Lucky Starzzz"
        ],
        MissC: "Suzie Toot",
        GoldenBoot: "Acacia Forgot",
        leverQueen: "Jewels Sparkles",
        leverNum: 3,
        lipSyncAssasin: "Jewels Sparkles",
        firstQueensSwaped: "Lucky Starzzz",
        secondQueensSwaped: "Onya Nurve"
    },
    {
        playerName: "Sam",
        playerRankings: [
            "Lexi Love",
            "Jewels Sparkles",
            "Sam Star",
            "Kori King",
            "Lana Ja'Rae",
            "Suzie Toot",
            "Onya Nurve",
            "Crystal Envy",
            "Arrietty",
            "Lydia B Kollins",
            "Lucky Starzzz",
            "Acacia Forgot",
            "Hormona Lisa",
            "Joella",
        ],
        playerWinners: [
            "Jewels Sparkles",
            "Suzie Toot",
            "Arrietty",
            "Suzie Toot",
            "Lexi Love",
            "Sam Star"
        ],
        MissC: "Lexi Love",
        GoldenBoot: "Hormona Lisa",
        leverQueen: "Lana Ja'Rae",
        leverNum: 4,
        lipSyncAssasin: "Arrietty",
        firstQueensSwaped: "Onya Nurve",
        secondQueensSwaped: "Lucky Starzzz"
    },
    {
        playerName: "Kdawg",
        playerRankings: [
            "Lexi Love",
            "Suzie Toot",
            "Onya Nurve",
            "Jewels Sparkles",
            "Sam Star",
            "Lucky Starzzz",
            "Lydia B Kollins",
            "Kori King",
            "Arrietty",
            "Lana Ja'Rae",
            "Crystal Envy",
            "Joella",
            "Hormona Lisa",
            "Acacia Forgot",
        ],
        playerWinners: [
            "Jewels Sparkles",
            "Onya Nurve",
            "Sam Star",
            "Suzie Toot",
            "Suzie Toot",
            "Lucky Starzzz"
        ],
        MissC: "Lexi Love",
        GoldenBoot: "Lana Ja'Rae",
        leverQueen: "Joella",
        leverNum: 4,
        lipSyncAssasin: "Crystal Envy",
        firstQueensSwaped: "Crystal Envy",
        secondQueensSwaped: "Onya Nurve"
    },
    {
        playerName: "Imma",
        playerRankings: [
            "Suzie Toot",
            "Lexi Love",
            "Kori King",
            "Jewels Sparkles",
            "Onya Nurve",
            "Arrietty",
            "Lydia B Kollins",
            "Lana Ja'Rae",
            "Lucky Starzzz",
            "Sam Star",
            "Joella",
            "Hormona Lisa",
            "Acacia Forgot",
            "Crystal Envy",
        ],
        playerWinners: [
            "Suzie Toot",
            "Onya Nurve",
            "Arrietty",
            "Suzie Toot",
            "Kori King",
            "Arrietty"
        ],
        MissC: "Lexi Love",
        GoldenBoot: "Joella",
        leverQueen: "Crystal Envy",
        leverNum: 2,
        lipSyncAssasin: "Arrietty",
        firstQueensSwaped: "Crystal Envy",
        secondQueensSwaped: "Onya Nurve"
    },
    {
        playerName: "Nathan",
        playerRankings: [
            "Lexi Love",
            "Kori King",
            "Jewels Sparkles",
            "Onya Nurve",
            "Suzie Toot",
            "Sam Star",
            "Lana Ja'Rae",
            "Arrietty",
            "Lucky Starzzz",
            "Lydia B Kollins",
            "Joella",
            "Acacia Forgot",
            "Crystal Envy",
            "Hormona Lisa",
        ],
        playerWinners: [
            "Jewels Sparkles",
            "Onya Nurve",
            "Jewels Sparkles",
            "Sam Star",
            "Arrietty",
            "Lana Ja'Rae"
        ],
        MissC: "Lucky Starzzz",
        GoldenBoot: "Joella",
        leverQueen: "Arrietty",
        leverNum: 2,
        lipSyncAssasin: "Lucky Starzzz",
        firstQueensSwaped: "Onya Nurve",
        secondQueensSwaped: "Crystal Envy"
    },
    {
        playerName: "Roudell",
        playerRankings: [
            "Lexi Love",
            "Onya Nurve",
            "Suzie Toot",
            "Lucky Starzzz",
            "Arrietty",
            "Kori King",
            "Lana Ja'Rae",
            "Crystal Envy",
            "Jewels Sparkles",
            "Sam Star",
            "Lydia B Kollins",
            "Hormona Lisa",
            "Acacia Forgot",
            "Joella",
        ],
        playerWinners: [
            "Jewels Sparkles",
            "Sam Star",
            "Arrietty",
            "Suzie Toot",
            "Kori King",
            "Lucky Starzzz"
        ],
        MissC: "Arrietty",
        GoldenBoot: "Joella",
        leverQueen: "Arrietty",
        leverNum: 6,
        lipSyncAssasin: "Acacia Forgot",
        firstQueensSwaped: "Onya Nurve",
        secondQueensSwaped: "Jewels Sparkles"
    },
    {
        playerName: "Alessandra",
        playerRankings: [
            "Lexi Love",
            "Onya Nurve",
            "Jewels Sparkles",
            "Sam Star",
            "Lucky Starzzz",
            "Suzie Toot",
            "Lana Ja'Rae",
            "Arrietty",
            "Kori King",
            "Crystal Envy",
            "Lydia B Kollins",
            "Joella",
            "Acacia Forgot",
            "Hormona Lisa",
        ],
        playerWinners: [
            "Jewels Sparkles",
            "Onya Nurve",
            "Arrietty",
            "Kori King",
            "Jewels Sparkles",
            "Lucky Starzzz"
        ],
        MissC: "Lexi Love",
        GoldenBoot: "Onya Nurve",
        leverQueen: "Lana Ja'Rae",
        leverNum: 4,
        lipSyncAssasin: "Jewels Sparkles",
        firstQueensSwaped: "Kori King",
        secondQueensSwaped: "Onya Nurve"
    },
    {
        playerName: "Hannah Kelly",
        playerRankings: [
            "Onya Nurve",
            "Jewels Sparkles",
            "Sam Star",
            "Lexi Love",
            "Suzie Toot",
            "Lana Ja'Rae",
            "Arrietty",
            "Lydia B Kollins",
            "Kori King",
            "Crystal Envy",
            "Acacia Forgot",
            "Lucky Starzzz",
            "Hormona Lisa",
            "Joella",
        ],
        playerWinners: [
            "Sam Star",
            "Suzie Toot",
            "Arrietty",
            "Jewels Sparkles",
            "Hormona Lisa",
            "Lydia B Kollins"
        ],
        MissC: "Lydia B Kollins",
        GoldenBoot: "Lucky Starzzz",
        leverQueen: "Lana Ja'Rae",
        leverNum: 4,
        lipSyncAssasin: "Onya Nurve",
        firstQueensSwaped: "Onya Nurve",
        secondQueensSwaped: "Lexi Love"
    },
    {
        playerName: "Tariq",
        playerRankings: [
            "Lexi Love",
            "Suzie Toot",
            "Jewels Sparkles",
            "Arrietty",
            "Onya Nurve",
            "Sam Star",
            "Lydia B Kollins",
            "Kori King",
            "Crystal Envy",
            "Joella",
            "Lana Ja'Rae",
            "Hormona Lisa",
            "Acacia Forgot",
            "",
        ],
        playerWinners: [
            "Sam Star",
            "Onya Nurve",
            "Arrietty",
            "Suzie Toot",
            "Lexi Love",
            ""
        ],
        MissC: "Kori King", 
        GoldenBoot: "Joella",
        leverQueen: "Onya Nurve",
        leverNum: 1,
        lipSyncAssasin: "Jewels Sparkles",
        firstQueensSwaped: "Kori King",
        secondQueensSwaped: "Suzie Toot"
    },
] 